 'Set your settings
Dim name(145)
Dim fullname(145)

Dim i

name(0) = "AVH.BR"
name(1) = "BEK.BR"
name(2) = "BLG.BR"
name(3) = "COL.BR"
name(4) = "DEL.BR"
name(5) = "DXB.BR"
name(6) = "FRB.BR"
name(7) = "GBL.BR"
name(8) = "INT.BR"
name(9) = "KBC.BR"
name(10) = "MOB.BR"
name(11) = "NYR.BR"
name(12) = "SOL.BR"
name(13) = "TLN.BR"
name(14) = "UCB.BR"
name(15) = "UMC.BR"
name(16) = "1151075.VI"
name(17) = "218214.VI"
name(18) = "414921.VI"
name(19) = "428837.VI"
name(20) = "430021.VI"
name(21) = "430590.VI"
name(22) = "431965.VI"
name(23) = "ANDR.VI"
name(24) = "CAI.VI"
name(25) = "CWI.VI"
name(26) = "EBS.VI"
name(27) = "IIA.VI"
name(28) = "LNZ.VI"
name(29) = "POST.VI"
name(30) = "RBI.VI"
name(31) = "SBO.VI"
name(32) = "STR.VI"
name(33) = "VER.VI"
name(34) = "VIG.VI"
name(35) = "ZAG.VI"
name(36) = "AC.PA"
name(37) = "ACA.PA"
name(38) = "AI.PA"
name(39) = "ALO.PA"
name(40) = "ALU.PA"
name(41) = "BN.PA"
name(42) = "BNP.PA"
name(43) = "CA.PA"
name(44) = "CAP.PA"
name(45) = "CS.PA"
name(46) = "DG.PA"
name(47) = "EAD.PA"
name(48) = "EDF.PA"
name(49) = "EI.PA"
name(50) = "EN.PA"
name(51) = "FP.PA"
name(52) = "FTE.PA"
name(53) = "GLE.PA"
name(54) = "GSZ.PA"
name(55) = "KN.PA"
name(56) = "LG.PA"
name(57) = "MC.PA"
name(58) = "ML.PA"
name(59) = "MT.PA"
name(60) = "OR.PA"
name(61) = "PP.PA"
name(62) = "PUB.PA"
name(63) = "RI.PA"
name(64) = "RNO.PA"
name(65) = "SAN.PA"
name(66) = "SEV.PA"
name(67) = "SGO.PA"
name(68) = "STM.PA"
name(69) = "SU.PA"
name(70) = "TEC.PA"
name(71) = "UG.PA"
name(72) = "UL.PA"
name(73) = "VIE.PA"
name(74) = "VIV.PA"
name(75) = "VK.PA"
name(76) = "ADS.DE"
name(77) = "ALV.DE"
name(78) = "BAS.DE"
name(79) = "BAYN.DE"
name(80) = "BEI.DE"
name(81) = "BMW.DE"
name(82) = "CBK.DE"
name(83) = "DAI.DE"
name(84) = "DB1.DE"
name(85) = "DBK.DE"
name(86) = "DPW.DE"
name(87) = "DTE.DE"
name(88) = "EOAN.DE"
name(89) = "FME.DE"
name(90) = "FRE.DE"
name(91) = "HEI.DE"
name(92) = "HEN3.DE"
name(93) = "IFX.DE"
name(94) = "LHA.DE"
name(95) = "LIN.DE"
name(96) = "MAN.DE"
name(97) = "MEO.DE"
name(98) = "MRK.DE"
name(99) = "MUV2.DE"
name(100) = "RWE.DE"
name(101) = "SAP.DE"
name(102) = "SDF.DE"
name(103) = "SIE.DE"
name(104) = "TKA.DE"
name(105) = "VOW3.DE"
name(106) = "A2A.MI"
name(107) = "AGL.MI"
name(108) = "ATL.MI"
name(109) = "AZM.MI"
name(110) = "BMPS.MI"
name(111) = "BP.MI"
name(112) = "BPE.MI"
name(113) = "BZU.MI"
name(114) = "CPR.MI"
name(115) = "DIA.MI"
name(116) = "EGPW.MI"
name(117) = "ENEL.MI"
name(118) = "ENI.MI"
name(119) = "EXO.MI"
name(120) = "F.MI"
name(121) = "FI.MI"
name(122) = "FNC.MI"
name(123) = "G.MI"
name(124) = "IPG.MI"
name(125) = "ISP.MI"
name(126) = "LTO.MI"
name(127) = "LUX.MI"
name(128) = "MB.MI"
name(129) = "MED.MI"
name(130) = "MS.MI"
name(131) = "PC.MI"
name(132) = "PLT.MI"
name(133) = "PMI.MI"
name(134) = "PRY.MI"
name(135) = "SFER.MI"
name(136) = "SPM.MI"
name(137) = "SRG.MI"
name(138) = "STM.MI"
name(139) = "STS.MI"
name(140) = "TEN.MI"
name(141) = "TIT.MI"
name(142) = "TOD.MI"
name(143) = "TRN.MI"
name(144) = "UBI.MI"
name(145) = "UCG.MI"

fullname(0) = "ACKERMANS"
fullname(1) = "BEKAERT"
fullname(2) = "BELGACOM"
fullname(3) = "COLRUYT"
fullname(4) = "GROUPE DELHAIZE"
fullname(5) = "DEXIA"
fullname(6) = "AGEAS"
fullname(7) = "GBL"
fullname(8) = "ANHEUS.-BUSCH INBEV"
fullname(9) = "KBC GR"
fullname(10) = "MOBISTAR"
fullname(11) = "NYRSTAR"
fullname(12) = "SOLVAY"
fullname(13) = "TELENET GROUP HOLD"
fullname(14) = "UCB"
fullname(15) = "UMICORE"
fullname(16) = "TELEKOM AUSTRIA"
fullname(17) = "MAYR-MELNHOF KARTON"
fullname(18) = "VOESTALPINE"
fullname(19) = "EVN"
fullname(20) = "OMV"
fullname(21) = "RHI"
fullname(22) = "WIENERBERGER AG"
fullname(23) = "ANDRITZ"
fullname(24) = "CA IMMOB ANLAGEN"
fullname(25) = "CONWERT IMMOBIL INV"
fullname(26) = "ERSTE GROUP BANK"
fullname(27) = "IMMOFINANZ"
fullname(28) = "LENZING"
fullname(29) = "OESTERREICH POST"
fullname(30) = "RAIFF BANK INTER"
fullname(31) = "SCHOELLER-BLECKMANN"
fullname(32) = "STRABAG"
fullname(33) = "VERBUND"
fullname(34) = "VIENNA INSURANCE GR"
fullname(35) = "ZUMTOBEL"
fullname(36) = "ACCOR"
fullname(37) = "CREDIT AGRICOLE"
fullname(38) = "AIR LIQUIDE"
fullname(39) = "ALSTOM"
fullname(40) = "ALCATEL-LUCENT"
fullname(41) = "DANONE"
fullname(42) = "BNP PARIBAS"
fullname(43) = "CARREFOUR"
fullname(44) = "CAP GEMINI"
fullname(45) = "AXA"
fullname(46) = "VINCI"
fullname(47) = "EADS"
fullname(48) = "EDF"
fullname(49) = "ESSILOR INTL"
fullname(50) = "BOUYGUES"
fullname(51) = "TOTAL"
fullname(52) = "FRANCE TELECOM"
fullname(53) = "STE GENERALE-A-"
fullname(54) = "GDF SUEZ"
fullname(55) = "NATIXIS"
fullname(56) = "LAFARGE"
fullname(57) = "LVMH"
fullname(58) = "MICHELIN"
fullname(59) = "ARCELORMITTAL REG"
fullname(60) = "L'OREAL"
fullname(61) = "PPR"
fullname(62) = "PUBLICIS GROUPE"
fullname(63) = "PERNOD RICARD"
fullname(64) = "RENAULT"
fullname(65) = "SANOFI"
fullname(66) = "SUEZ ENV. CPY"
fullname(67) = "SAINT GOBAIN"
fullname(68) = "STMICROELECTRONICS"
fullname(69) = "SCHNEIDER ELECTRIC"
fullname(70) = "TECHNIP"
fullname(71) = "PEUGEOT"
fullname(72) = "UNIBAIL-RODAMCO"
fullname(73) = "VEOLIA ENVIRONN."
fullname(74) = "VIVENDI"
fullname(75) = "VALLOUREC"
fullname(76) = "ADIDAS N"
fullname(77) = "ALLIANZ N"
fullname(78) = "BASF N"
fullname(79) = "BAYER N"
fullname(80) = "BEIERSDORF"
fullname(81) = "BMW"
fullname(82) = "COMMERZBANK"
fullname(83) = "DAIMLER N"
fullname(84) = "DEUTSCHE BOERSE N"
fullname(85) = "DEUTSCHE BANK N"
fullname(86) = "DEUTSCHE POST N"
fullname(87) = "DEUTSCHE TELEKOM N"
fullname(88) = "E.ON N"
fullname(89) = "FRESENIUS MED CARE"
fullname(90) = "FRESENIUS"
fullname(91) = "HEIDELBERGCEMENT"
fullname(92) = "HENKEL VZ"
fullname(93) = "INFINEON TECHNOLO N"
fullname(94) = "DT.LUFTHANSA N"
fullname(95) = "LINDE"
fullname(96) = "MAN"
fullname(97) = "METRO"
fullname(98) = "MERCK"
fullname(99) = "MUNICHRE"
fullname(100) = "RWE"
fullname(101) = "SAP"
fullname(102) = "K+S N"
fullname(103) = "SIEMENS N"
fullname(104) = "THYSSENKRUPP"
fullname(105) = "VOLKSWAGEN VZ"
fullname(106) = "A2A"
fullname(107) = "AUTOGRILL"
fullname(108) = "ATLANTIA"
fullname(109) = "AZIMUT HOLDING"
fullname(110) = "BANCA MPS"
fullname(111) = "BANCO POPOLARE"
fullname(112) = "BCA POP. EMILIA R."
fullname(113) = "BUZZI UNICEM"
fullname(114) = "CAMPARI"
fullname(115) = "DIASORIN"
fullname(116) = "ENEL GREEN POWER"
fullname(117) = "ENEL"
fullname(118) = "ENI"
fullname(119) = "EXOR"
fullname(120) = "FIAT"
fullname(121) = "FIAT INDUSTRIAL"
fullname(122) = "FINMECCANICA"
fullname(123) = "GENERALI"
fullname(124) = "IMPREGILO"
fullname(125) = "INTESA SANPAOLO"
fullname(126) = "LOTTOMATICA"
fullname(127) = "LUXOTTICA GROUP"
fullname(128) = "MEDIOBANCA"
fullname(129) = "MEDIOLANUM"
fullname(130) = "MEDIASET"
fullname(131) = "PIRELLI & C"
fullname(132) = "PARMALAT"
fullname(133) = "BCA POP. MILANO"
fullname(134) = "PRYSMIAN"
fullname(135) = "FERRAGAMO"
fullname(136) = "SAIPEM"
fullname(137) = "SNAM"
fullname(138) = "STMICROELECTRONICS"
fullname(139) = "ANSALDO STS"
fullname(140) = "TENARIS"
fullname(141) = "TELECOM ITALIA"
fullname(142) = "TOD'S"
fullname(143) = "TERNA"
fullname(144) = "UBI BANCA"
fullname(145) = "UNICREDIT"

Dim j

j = 0


For Each i In name 

j = j + 1

strFileURL = "http://ichart.finance.yahoo.com/table.csv?s=" & i


strHDLocation = fullname(j) & ".csv"

   ' Fetch the file

    Set objXMLHTTP = CreateObject("MSXML2.XMLHTTP")


    objXMLHTTP.open "GET", strFileURL, false
    objXMLHTTP.send()

    If objXMLHTTP.Status = 200 Then

      Set objADOStream = CreateObject("ADODB.Stream")
      objADOStream.Open
      objADOStream.Type = 1 'adTypeBinary

      objADOStream.Write objXMLHTTP.ResponseBody

      objADOStream.Position = 0    'Set the stream position to the start

      Set objFSO = Createobject("Scripting.FileSystemObject")
        If objFSO.Fileexists(strHDLocation) Then objFSO.DeleteFile strHDLocation
      Set objFSO = Nothing
      objADOStream.SaveToFile strHDLocation
      objADOStream.Close
      Set objADOStream = Nothing
    End if

    Set objXMLHTTP = Nothing


Next
